{
 "title": "API Usage",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(vdm_sf_app_call_total, app)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values(vdm_sf_app_call_total{app=\"$app\",  route!=\"vdm_prometheus_metrics\",  route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}, route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "3xx Percents",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(vdm_sf_app_response_code_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\", http_code=~\"3.+\"}[$__range])) * 100 / sum(rate(vdm_sf_app_response_code_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}[$__range]))"
    }
   ]
  },
  {
   "title": "4xx Percent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(vdm_sf_app_response_code_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\", http_code=~\"4.+\"}[$__range])) * 100 / sum(rate(vdm_sf_app_response_code_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}[$__range]))"
    }
   ]
  },
  {
   "title": "5xx Percent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(vdm_sf_app_response_code_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\", http_code=~\"5.+\"}[$__range])) * 100 / sum(rate(vdm_sf_app_response_code_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}[$__range]))"
    }
   ]
  },
  {
   "title": "2xx Percent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(vdm_sf_app_response_code_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\", http_code=~\"2.+\"}[$__range])) * 100 / sum(rate(vdm_sf_app_response_code_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vdm_sf_app_call_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Rate total (per seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vdm_sf_app_response_code_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}[$__interval])) by (route)"
    }
   ]
  },
  {
   "title": "Rate per http code (per seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vdm_sf_app_response_code_total{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}[$__interval])) by (route, http_code)"
    }
   ]
  },
  {
   "title": "Average memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(vdm_sf_app_memory_usage{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(vdm_sf_app_memory_usage{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}) by (route)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(vdm_sf_app_response_time{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(vdm_sf_app_response_time{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}) by (route)"
    }
   ]
  },
  {
   "title": "Average response size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vdm_sf_app_response_size{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"})"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "avg(vdm_sf_app_response_size{app=\"$app\", route=~\"$route\", route!=\"vdm_prometheus_metrics\", route!=\"vdm_version_route\", route!=\"vdm_healthcheck_liveness\", route!=\"vdm_healthcheck_readiness\", route !~\".+swagger\", route !=\"\"}) by (route)"
    }
   ]
  }
 ]
}